### PR TITLE
Cancel syscall

### LINKED ISSUE #21: Popup input must be cancelable
Closing the popup windows of input, yield unexpected results:

* reading numbers raise a runtime exception.
* ReadString return "uninitializedValue"
* ReadChar return the ascii code of `u`

In these two last case, the program continues and might be stuck in an uninterruptible loop of input :(

```asm
li a7, 12
loop: ecall
j loop
```

In fact, on cancel, a special string `"uninitializedValue"` is used as a sentinel `JOptionPane.UNINITIALIZED_VALUE`, but is not handled by rars, letting the code play as is as if "uninitializedValue" was set by the user.

TODO:

* make cancel cause a simulation error that stop the program (see how it is done for conversion error with numbers)
* optionally use `OK_CANCEL_OPTION` to display a Cancel button

### PR DESCRIPTION
**Pull request by privat**
The user can now cancel sycalls with popup. A cancel button is present and has the same effect that a breakpoint.

Close #21

### CODE REVIEW

File: src/rars/riscv/syscalls/SyscallReadChar.java [hunk 1]
```diff
@@ -1,8 +1,9 @@
 package rars.riscv.syscalls;
 
-import rars.ExitingException;
-import rars.ProgramStatement;
+import rars.*;
 import rars.riscv.AbstractSyscall;
+import rars.riscv.Instruction;
+import rars.riscv.hardware.Register;
```
Comment (Shin-703) [inline src/rars/riscv/syscalls/SyscallReadChar.java:6]: Do we need to add those two lines (5 and 6)? I don't see those used
